### ISSUE TITLE
keycloak authenticate

### ISSUE THREAD

**Issue by claudineigomes** [atende/audit-view#21]
When npm run start, the app is authenticating in keycloak all time, and is not getting once the token.

The app get the 
http://localhost:4200/#state=8e29794d-13a6-4f26-b2e8-58855548981d&code=WOwt_3zVwDpxuBoEfLrEPBBeiU2t86jakdCeQOzqxPQ.e84339c9-cd07-439e-8633-e58bbecf006e
and then is getting another is less one seccond. @giovannicandido

**Comment by giovannicandido** [comment]
I will check this soon

**Comment by claudineigomes** [comment]
@giovannicandido this problem was solved. The configuration of keycloak was incorrect. Thank you.
